# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/annotations.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import http_pb2 as api_dot_http__pb2
from api import micro_pb2 as api_dot_micro__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pi/annotations.proto\x12\tmicro.api\x1a\x0e\x61pi/http.proto\x1a\x0f\x61pi/micro.proto\x1a google/protobuf/descriptor.proto:D\n\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xa6\xfd\x9f\x1f \x01(\x0b\x32\x13.micro.api.HttpRule:O\n\x0cmicro_method\x12\x1e.google.protobuf.MethodOptions\x18\xa7\xfd\x9f\x1f \x01(\x0b\x32\x16.micro.api.MicroMethod:R\n\rmicro_service\x12\x1f.google.protobuf.ServiceOptions\x18\xa7\xfd\x9f\x1f \x01(\x0b\x32\x17.micro.api.MicroServiceBN\n\tmicro.apiB\x10\x41nnotationsProtoP\x01Z&go.unistack.org/micro-proto/v3/api;api\xa2\x02\x04MAPIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.annotations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tmicro.apiB\020AnnotationsProtoP\001Z&go.unistack.org/micro-proto/v3/api;api\242\002\004MAPI'
# @@protoc_insertion_point(module_scope)
